<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251212215912 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, weighable BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A29DA1B88C03F15C ON correction (employee_id)');
        $this->addSql('CREATE TABLE correction_item (new_inventory DOUBLE PRECISION NOT NULL, product_id INT NOT NULL, correction_id INT NOT NULL, PRIMARY KEY (product_id, correction_id))');
        $this->addSql('CREATE INDEX IDX_FEA49D784584665A ON correction_item (product_id)');
        $this->addSql('CREATE INDEX IDX_FEA49D7894AE086B ON correction_item (correction_id)');
        $this->addSql('CREATE TABLE destruction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_48CE57A68C03F15C ON destruction (employee_id)');
        $this->addSql('CREATE TABLE destruction_item (quantity DOUBLE PRECISION NOT NULL, reason TEXT DEFAULT NULL, product_id INT NOT NULL, destruction_id INT NOT NULL, PRIMARY KEY (product_id, destruction_id))');
        $this->addSql('CREATE INDEX IDX_4812766F4584665A ON destruction_item (product_id)');
        $this->addSql('CREATE INDEX IDX_4812766F3292C08E ON destruction_item (destruction_id)');
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON employee (username)');
        $this->addSql('CREATE TABLE local_sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total DOUBLE PRECISION NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D954AAD68C03F15C ON local_sale (employee_id)');
        $this->addSql('CREATE TABLE local_sale_item (quantity DOUBLE PRECISION NOT NULL, unit_price_at_sale DOUBLE PRECISION NOT NULL, product_id INT NOT NULL, local_sale_id INT NOT NULL, PRIMARY KEY (product_id, local_sale_id))');
        $this->addSql('CREATE INDEX IDX_5D12DEA74584665A ON local_sale_item (product_id)');
        $this->addSql('CREATE INDEX IDX_5D12DEA7D7AB4DE5 ON local_sale_item (local_sale_id)');
        $this->addSql('CREATE TABLE mobile_sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT NOT NULL, total DOUBLE PRECISION NOT NULL, paid BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE mobile_sale_item (quantity DOUBLE PRECISION NOT NULL, unit_price_at_sale DOUBLE PRECISION NOT NULL, product_id INT NOT NULL, mobile_sale_id INT NOT NULL, PRIMARY KEY (product_id, mobile_sale_id))');
        $this->addSql('CREATE INDEX IDX_2F4B1AA44584665A ON mobile_sale_item (product_id)');
        $this->addSql('CREATE INDEX IDX_2F4B1AA4AAD4859D ON mobile_sale_item (mobile_sale_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, unit_price DOUBLE PRECISION NOT NULL, barcode VARCHAR(255) DEFAULT NULL, inventory DOUBLE PRECISION NOT NULL, category_id INT NOT NULL, vat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADB5B63A6B ON product (vat_id)');
        $this->addSql('CREATE TABLE purchase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total DOUBLE PRECISION NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6117D13B8C03F15C ON purchase (employee_id)');
        $this->addSql('CREATE TABLE purchase_item (quantity DOUBLE PRECISION NOT NULL, unit_price_at_purchase DOUBLE PRECISION NOT NULL, product_id INT NOT NULL, purchase_id INT NOT NULL, PRIMARY KEY (product_id, purchase_id))');
        $this->addSql('CREATE INDEX IDX_6FA8ED7D4584665A ON purchase_item (product_id)');
        $this->addSql('CREATE INDEX IDX_6FA8ED7D558FBEB9 ON purchase_item (purchase_id)');
        $this->addSql('CREATE TABLE vat_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE correction ADD CONSTRAINT FK_A29DA1B88C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE correction_item ADD CONSTRAINT FK_FEA49D784584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE correction_item ADD CONSTRAINT FK_FEA49D7894AE086B FOREIGN KEY (correction_id) REFERENCES correction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destruction ADD CONSTRAINT FK_48CE57A68C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destruction_item ADD CONSTRAINT FK_4812766F4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destruction_item ADD CONSTRAINT FK_4812766F3292C08E FOREIGN KEY (destruction_id) REFERENCES destruction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE local_sale ADD CONSTRAINT FK_D954AAD68C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE local_sale_item ADD CONSTRAINT FK_5D12DEA74584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE local_sale_item ADD CONSTRAINT FK_5D12DEA7D7AB4DE5 FOREIGN KEY (local_sale_id) REFERENCES local_sale (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mobile_sale_item ADD CONSTRAINT FK_2F4B1AA44584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mobile_sale_item ADD CONSTRAINT FK_2F4B1AA4AAD4859D FOREIGN KEY (mobile_sale_id) REFERENCES mobile_sale (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADB5B63A6B FOREIGN KEY (vat_id) REFERENCES vat_rate (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_item ADD CONSTRAINT FK_6FA8ED7D4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_item ADD CONSTRAINT FK_6FA8ED7D558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE correction DROP CONSTRAINT FK_A29DA1B88C03F15C');
        $this->addSql('ALTER TABLE correction_item DROP CONSTRAINT FK_FEA49D784584665A');
        $this->addSql('ALTER TABLE correction_item DROP CONSTRAINT FK_FEA49D7894AE086B');
        $this->addSql('ALTER TABLE destruction DROP CONSTRAINT FK_48CE57A68C03F15C');
        $this->addSql('ALTER TABLE destruction_item DROP CONSTRAINT FK_4812766F4584665A');
        $this->addSql('ALTER TABLE destruction_item DROP CONSTRAINT FK_4812766F3292C08E');
        $this->addSql('ALTER TABLE local_sale DROP CONSTRAINT FK_D954AAD68C03F15C');
        $this->addSql('ALTER TABLE local_sale_item DROP CONSTRAINT FK_5D12DEA74584665A');
        $this->addSql('ALTER TABLE local_sale_item DROP CONSTRAINT FK_5D12DEA7D7AB4DE5');
        $this->addSql('ALTER TABLE mobile_sale_item DROP CONSTRAINT FK_2F4B1AA44584665A');
        $this->addSql('ALTER TABLE mobile_sale_item DROP CONSTRAINT FK_2F4B1AA4AAD4859D');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADB5B63A6B');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B8C03F15C');
        $this->addSql('ALTER TABLE purchase_item DROP CONSTRAINT FK_6FA8ED7D4584665A');
        $this->addSql('ALTER TABLE purchase_item DROP CONSTRAINT FK_6FA8ED7D558FBEB9');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE correction');
        $this->addSql('DROP TABLE correction_item');
        $this->addSql('DROP TABLE destruction');
        $this->addSql('DROP TABLE destruction_item');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE local_sale');
        $this->addSql('DROP TABLE local_sale_item');
        $this->addSql('DROP TABLE mobile_sale');
        $this->addSql('DROP TABLE mobile_sale_item');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE purchase');
        $this->addSql('DROP TABLE purchase_item');
        $this->addSql('DROP TABLE vat_rate');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
